version: '3.8'

services:
  db:
    image: postgres:16.8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_file_helper
      POSTGRES_USER: file_helper
      POSTGRES_PASSWORD: 5288
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./djangoProject:/djangoProject
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
volumes:
  postgres_data:
