# Generated by Django 5.2.1 on 2025-05-16 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10)),
                ('desc', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='FileBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('file_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_helper.filetype')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.UUIDField()),
                ('file_name', models.CharField()),
                ('file_body', models.CharField()),
                ('is_merge', models.CharField(max_length=1)),
                ('batch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_helper.filebatch')),
                ('file_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_helper.filetype')),
            ],
        ),
    ]
